### ISSUE TITLE
Some CSVs fail when the Excel version succeeds

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/ams#399]
We have several anecdotal cases of a user submitted a CSV to the Asset CSV ingest and having it fail to even start the batch. When the Excel file that was used to save the CSV file from is ingested, the batch doesn't fail (however, in at least one of these cases  all of the individual items in the batch did fail).  Since we've noticed this was a recurring problem, we've been able to get one example of both the CSV and Excel files, which I hope we can use to determine why this is happening. 
Here's the Excel file:
[BillMoyers_AMS2_Ingest.xlsx](https://github.com/WGBH-MLA/ams/files/4077430/BillMoyers_AMS2_Ingest.xlsx)

Github won't let me upload the .csv file, but I took that file and just changed the extension to .txt so GitHub would let me upload. You should be able to just change the extension back to .csv, but otherwise, reference the dev team channel in Slack, where I've also uploaded them. 
[BillMoyers_AMS2_Ingest.txt](https://github.com/WGBH-MLA/ams/files/4077445/BillMoyers_AMS2_Ingest.txt)

**Comment by jasoncorum** [comment]
I was able to successfully ingest a CSV locally that I'll post in Slack. It was saved as a UTF-8 CSV in SublimeText and it adds all the expected headers. Since it appears the expected headers are critical to the success of a CSV ingest, I'm going to add an early check for that with a good error message. Then, I want to bubble up an error on Excel formatted dates to the User. Finally, I want to see what we can do about this Mac Excel file formatting nonsense we keep getting.
