### ISSUE TITLE
Users should be able to add annotation type in UI from dropdown

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/ams#442]
As an archivist, I need to be able to update annotation type with all of the [controlled vocabulary](https://wiki.wgbh.org/display/MLA/Custom+Annotation+Types+for+AAPB+Admin+Data) in a dropdown from the UI, so that I can add metadata.

Done When: users can add annotation types to records.
Done When: organization is exported in PBCore

**Comment by jasoncorum** [comment]
This actually ended up being an additional field on the AAPBAdminData based on documents from the project.

**Comment by jasoncorum** [comment]
Moving this back to in progess because I was wrong above. However, we decided to that the annotation data should be encapsulated within the AAPBAdminData object, so our approach will be to add the "annotation types" (https://wiki.wgbh.org/pages/viewpage.action?spaceKey=MLA&title=Custom+Annotation+Types+for+AAPB+Admin+Data) as additional fields on the AAPBAdmin data that will be exported as PBCore annotations.
