### ISSUE TITLE
WIPR records are not updating on AAPB

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ams#876]
# Details 
I just updated some records on AMS2, pushed them to the AAPB but they are still listed as Unknown and being displayed weird. Could someone take a look at them?
cpb-aacip-f01de070593
cpb-aacip-4f3700726be.
cpb-aacip-601b41b7bae
cpb-aacip-9c5a99bb1a6
cpb-aacip-6e49ea49899
cpb-aacip-c4c070ef62c
cpb-aacip-9bd03890121
cpb-aacip-4cd9f204ac1
cpb-aacip-4cb1bac3a1b.
cpb-aacip-7eff26cca2a
cpb-aacip-b8e9d349b3c
cpb-aacip-9124f2364b7

Submitted by: Caroline
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by afred** [comment]
repushed
- [x] cpb-aacip-f01de070593
- [x] cpb-aacip-4f3700726be
- [x] cpb-aacip-601b41b7bae
- [x] cpb-aacip-9c5a99bb1a6
- [x] cpb-aacip-6e49ea49899
- [x] cpb-aacip-c4c070ef62c
- [x] cpb-aacip-9bd03890121
- [x] cpb-aacip-4cd9f204ac1
- [x] cpb-aacip-4cb1bac3a1b
- [x] cpb-aacip-7eff26cca2a
- [x] cpb-aacip-b8e9d349b3c
- [x] cpb-aacip-9124f2364b7

**Comment by afred** [comment]
@czo-mango these were all failing due to a duplicate `<instantiationLocation>` element in their pbcore.

To fix them, you can open the "Edit Instantiation" form, and explicitly remove the empty Location by clicking the little "remove" link.

However, this is a legit bug, because it's erroneously adding the extra empty ones automatically. So it's good we found it, but super annoying! Sorry you bumped into it. I just [filed a bug for it](https://github.com/WGBH-MLA/ams/issues/886).

In the meantime, check these records ☝️ and if they are good, we can close this ticket.

**Comment by czo-mango** [comment]
Thanks Drew!! That is so strange!!! I'm going to deep dive now!

**Comment by czo-mango** [comment]
Yep! These are all on the AAPB now. We can close this ticket :)

**Comment by ekemeyer** [comment]
Thanks Drew and Caroline!
